'''config.py

	Sets global locations for state-flu project allowing all scripts and functions to access
	central directories such as data and output.

	Also defines global constants such as state abbreviations.

'''

# define project top-level directory.
import os
import numpy as np

HOME_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# define data directories
DATA_DIR = HOME_DIR + '/data'
GT_DIR = DATA_DIR + '/GT'
ATH_LOC = DATA_DIR + '/athena/ATHdata.csv'
STATE_ILI_LOC = DATA_DIR + '/ILI/States_ILI.csv'

# define output directory
STATES_DIR = HOME_DIR + '/results'

STATES = ("AL,AK,AZ,AR,CA,CO,CT,DE,FL,GA,HI,ID,IL,IN,IA,KS,KY,LA,ME,MD,MA,MI,MN,MS,MO,"
          "MT,NE,NV,NH,NJ,NM,NY,NC,ND,OH,OK,OR,PA,RI,SC,SD,TN,TX,UT,VT,VA,WA,WV,WI,WY"
          ).split(',')

USE_DATA_FROM = '2009-10-04'
END_DATE = '2017-05-14'


# VARIABLES
STATE_FOLDER = '/Users/leonardo/Desktop/state-flu/results/'
COLORS =  ['orangered','skyblue','green','mediumslateblue','darkseagreen','lightsalmon', 'darkblue','orangered' , 'c', 'dodgerblue',\
'khaki','rosybrown','seagreen','mediumpurple', 'mediumturquoise', 'lightslategray','goldenrod', 'thistle'] # https://matplotlib.org/examples/color/named_colors.html
OVERVIEW_FOLDER = '_overview'
ALL_STATES = ['MA', 'WA',	'NJ',	'TN',	'VT',	'OR', 'NY'	, 'ME', 'AZ', \
'AK',	'AL',	'AR',	'DE',	'GA',	'ID',	'KS',	'KY',	'LA',	'MD', \
'MI','MN',	'NC',	'ND',	'NE',	'NH',	'NM',	'NV',	'OH',	'PA',	\
'RI',	'SC',	'SD',	'TX',	'UT',	'VA',	'WI',	'WV']
FULL_DATA_FILE = '_merged_data.csv'

# Documents generated by state_vis for the ranking and its corresponding values
mat_ST_RANKS = 'mat_metric_rankings.csv'
mat_ST_RANKS_V = 'mat_metric_values.csv'

# TEMPORAL
STATE_COLOR_DICT = {'ARGO(gt,ath)': 'lightsalmon', "AR52": 'mediumslateblue' ,"ARGO(gt)": 'darkblue', 'GFT': 'skyblue' }



LATAM_FOLDER = '/Users/leonardo/Desktop/latam-flu/LATAM/'
LATAM_COUNTRIES = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Mexico', 'Paraguay', 'Peru', 'Uruguay']
LATAM_COUNTRIES_short = ['AR', 'BO', 'BR', 'CL', 'MX', 'PE', 'PY', 'UY']
LATAM_STARTDATE = '2009-01-05'
LATAM_ENDDATE = '2017-04-10'

LATAM_SEASON_IND =  np.array([1, 52, 53, 104, 105, 156, 157, 209, 210, 261, 262, \
313, 314, 365, 366, 417, 418, 432]) -1

# Folder structure strings
LATAM_tableFile = '_table.csv'
LATAM_predFile = '_preds.csv'
LATAM_tableTitles = ['Metric', 'Y2009', 'Y2010', 'Y2011', 'S2012', 'Y2013', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'ALL_PERIOD', 'GFT_PERIOD']
LATAM_overviewFolder = '_overview/'
LATAM_articleFolder = '/Users/leonardo/Desktop/latam-flu/paper_plots'
LATAM_gtDataFile = '_GTdata.csv'


#------------------ PYARGO

TARGET = 'ILI' #'_TARGET'
TRAINING_WINDOW_SIZE_DEFAULT = 26
TRAINING_WINDOW_TYPE_DEFAULT = 'static'
FEATURE_PREPROCESSING_DEFAULT = 'unnormalized'
N_AR_LAGS_DEFAULT = 52


TXT_DATA = 'data_params.txt'
TXT_EXPERIMENT = 'experiment_params.txt'
PICKLE_DATA = 'data_params.pickle'
PICKLE_EXPERIMENT = 'experiment_params.pickle'
PICKLE_ARGONET_CHECKPOINT = 'checkpoint.pickle'

ID_DATA = 'merged_data.csv'
ID_PREDS = 'preds.csv'
ID_COEFF = 'coefficients.csv'
ID_HPARAMS = 'hyper_params.csv'
ID_METRICS = 'metrics.csv'
ID_EFFTEST = 'efficiencyTest.csv'

CSV_METRICS_CONDENSED = 'metrics_condensed.csv'
CSV_METRICS_EXTRACTED = 'metrics_extracted.csv'
CSV_ARGONET_DATA_ARGO = 'ARGONET_argodata.csv'
CSV_ARGONET_DATA_ILI = 'ARGONET_ilidata.csv'
CSV_ARGONET_DATA_AR = 'ARGONET_ardata.csv'


MISSING_DATA = float('NaN')
NAN_TO_VALUE = .5
